apiVersion: v1
kind: Service
metadata:
  name: {{ include "atcassembly.fullname" . }}
  labels:
    {{- include "atcassembly.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-port
      port: {{ .Values.app.httpport }}
      targetPort: http
      {{- if contains "NodePort" .Values.service.type }}
      nodePort: {{ .Values.service.ports.nodePort }}
      {{- end }}
      {{- if .Values.dev }}
    - name: remote-debug
      protocol: TCP
      port: 8000
      targetPort: 8000
      {{- if contains "NodePort" .Values.service.type }}
      nodePort: {{ .Values.service.ports.debugPort }}
      {{- end }}
      {{- end }}
  selector:
    {{- include "atcassembly.selectorLabels" . | nindent 4 }}
