# permissions for end users to edit dummyservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummyservice-editor-role
rules:
- apiGroups:
  - attwin.airlab.aero
  resources:
  - dummyservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - attwin.airlab.aero
  resources:
  - dummyservices/status
  verbs:
  - get
